# Site settings
title: Darnell Henry
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Darnell Henry
user_description: Full stack software engineer with skills in micro-services, cloud technology, artificial intelligence, object oriented programming, event sourcing, containerization, dev ops, and many more.
user_title: Software Engineer
email: darnelljh@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: darnell-henry-b3571619
github_username:  darnell-jh
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

